[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
askama_actix = "0.14.0"
askama = "0.12.1"
serde = "1.0.198"
serde_derive = "1.0.199"
