[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
wasm-bindgen-futures = "0.4.42"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
